version: '3.8'

services:
  # 1. Имитатор датчика температуры
  temperature-api:
    build:
      context: ./temperature-api
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      # Для Flask
      - FLASK_ENV=development
    restart: always

  # 2. База данных PostgreSQL для smart_home
  smart_home_db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smarthome_db
    volumes:
      # Монтирование скрипта инициализации
      - ./smart_home/init.sql:/docker-entrypoint-initdb.d/init.sql
      # Для сохранения данных
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
