version: '3.8'

services:
  temperature-api:
    build:
      context: ./temperature-api
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - FLASK_ENV=development
    restart: always
  smart_home_db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smarthome_db
    volumes:

      - ./smart_home/init.sql:/docker-entrypoint-initdb.d/init.sql

      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
